### ISSUE TITLE
Attribute definition vector?

### ISSUE THREAD

**Issue by hanshuebner** [zcaudate/adi#10]
Not so much an actual issue, but rather a question: Why are attribute definitions in a schema expressed as a map in a vector?  What is the vector good for?  If there is a better place to discuss, please share.  Thanks!

**Comment by zcaudate** [comment]
Hey Hans,

The vector is there because you can define schemas in a nested map and there has to be a way to differentiate between schema keys and the schema values.

Currently, this is probably the best place to ask questions, otherwise, shoot me an email directly.

**Comment by hanshuebner** [comment]
I see - We will probably try to use flat schema definitions and preprocess
our schema definitions so that we do not have to spell out the extra
vectors.  It seems to me that nested schema definitions are not so vital,
but that is just my opinion...

adi is awesome, though, and I'm very happy that we don't need to write it
ourselves.  Thanks for making it available, and thanks for getting back!
Maybe you could consider opening a https://gitter.im/ chat as a general
discussion channel so that the issues are not cluttered with random
non-issues?

**Comment by zcaudate** [comment]
That’s a great idea. i’ve created a room for the project.

https://gitter.im/zcaudate/adi <https://gitter.im/zcaudate/adi>
