### ISSUE TITLE
Support upserts

### ISSUE THREAD

**Issue by neverfox** [zcaudate/adi#12]
One of the nice features of raw datomic transaction processing is the automatic resolution of entities that results in an upsert. It would be nice if that were an option with adi.

**Comment by zcaudate** [comment]
can you give an example of what it potentially might look like. I think it may already be supported because it's using datomic internally.

**Comment by neverfox** [comment]
Hmm, okay. I thought I ran into it trying to insert but now that I think about it it might have been because of a bad schema definition (:value instead of :identity). I'll double check.

**Comment by neverfox** [comment]
Great library, btw.

**Comment by neverfox** [comment]
Yep that was it. Sorry for the false alarm.

**Comment by zcaudate** [comment]
glad it's sorted.... 

and please... if you find it useful, do find time to tweet/blog about it (and what you are building) as I'm hoping to get the word out!
