### ISSUE TITLE
documentation todo

### ISSUE THREAD

**Issue by clojens** [zcaudate/adi#6]
Hey, could you elaborate a bit on what you mean by 'self-referencing tutorial'. I'd be interested to see what the ideas are and perhaps contribute some if possible in first a brainstorm/discussion and perhaps (if I can) pick up some of the work. But I'd like to hear the intentions/idea on it before I would just start ^^

**Comment by neverfox** [comment]
Any progress with self-reference documentation. I haven't been able to crack this nut.

**Comment by zcaudate** [comment]
What are you planning to do with self-referencing?

I’ve got some simple graph-node linking examples going here:

http://docs.caudate.me/adi/adi-guide.html#pull 
4.2.6 :yield

but there are more complicated undocumented examples here:

adi.test.family
adi.process.normalise.common.alias-test
